# Prefer global cache, but currently this doesn't work with eslint
# because of: https://github.com/yarnpkg/berry/issues/706
enableGlobalCache: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-berry.js

packageExtensions:
  '@types/styled-components@*':
    dependencies:
      'react': '*'
  '@types/hoist-non-react-statics@*':
    dependencies:
      'react': '*'
  '@types/react-dom@*':
    dependencies:
      'react': '*'
